import { store } from '../store.js';
import CalendarField from './CalendarField.js?v=20260318-calendar-refresh-5';
import AdaptiveTable from './AdaptiveTable.js';
import CompactSelect from './CompactSelect.js';
import { exportToExcel } from './ExcelExport.js';

export default {
    components: {
        CalendarField,
        AdaptiveTable,
        CompactSelect
    },
    template: `
    <div class="crm-page">
        <div class="crm-page-header animate__animated animate__fadeIn">
            <div>
                <h2 class="crm-page-title">Sales Control Center</h2>
                <p class="crm-page-subtitle">Welcome back, <strong>{{ store.user?.full_name || store.user?.username }}</strong></p>
            </div>
            <div class="text-end d-none d-md-block">
                <span class="crm-date-pill">
                    <i class="bi bi-calendar3 text-primary"></i>{{ todayDate }}
                </span>
            </div>
        </div>

        <div v-if="store.hasRole(['Admin', 'Manager'])" class="mb-4">
            <div class="crm-toolbar">
                <div>
                    <h4 class="crm-section-title mb-1">Lead Reporting Dashboard</h4>
                    <p class="crm-inline-note mb-0">Track who created leads and monitor business development productivity.</p>
                </div>
            </div>

            <div class="row g-3 mb-3">
                <div class="col-md-3">
                    <div class="crm-stat-card h-100">
                        <div class="card-body">
                            <small class="text-muted d-block mb-1">Total Leads</small>
                            <div class="fs-4 fw-bold">{{ leadStats.total_leads }}</div>
                        </div>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="crm-stat-card h-100">
                        <div class="card-body">
                            <small class="text-muted d-block mb-1">New Leads</small>
                            <div class="fs-4 fw-bold text-info">{{ leadStats.status_breakdown.New || 0 }}</div>
                        </div>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="crm-stat-card h-100">
                        <div class="card-body">
                            <small class="text-muted d-block mb-1">Interested Leads</small>
                            <div class="fs-4 fw-bold text-primary">{{ leadStats.status_breakdown.Interested || 0 }}</div>
                        </div>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="crm-stat-card h-100">
                        <div class="card-body">
                            <small class="text-muted d-block mb-1">Converted Leads</small>
                            <div class="fs-4 fw-bold text-success">{{ leadStats.status_breakdown.Converted || 0 }}</div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="crm-card">
                <div class="crm-card-header">
                    <h5 class="crm-section-title">Leads Generated By Employee</h5>
                </div>
                <div class="crm-card-body">
                    <div class="crm-search-row">
                        <div class="crm-search">
                            <i class="bi bi-search crm-search-icon"></i>
                            <input type="text" class="form-control crm-search-input" v-model="employeeReportSearch" placeholder="Search by employee name or lead count">
                        </div>
                        <span class="crm-search-count-badge">{{ filteredEmployeePerformance.length }} Records</span>
                        <button class="crm-export-btn" :disabled="filteredEmployeePerformance.length === 0" @click="exportEmployeePerformance"><i class="bi bi-file-earmark-spreadsheet"></i>Export Excel</button>
                    </div>
                    <adaptive-table title="Leads Generated By Employee" :row-count="filteredEmployeePerformance.length">
                        <table class="table table-hover crm-table">
                            <thead>
                                <tr>
                                    <th>Employee</th>
                                    <th>Leads Generated</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr v-for="item in filteredEmployeePerformance" :key="item.employee_name">
                                    <td>{{ item.employee_name }}</td>
                                    <td>{{ item.lead_count }}</td>
                                </tr>
                                <tr v-if="filteredEmployeePerformance.length === 0">
                                    <td colspan="2" class="text-center py-4">No lead productivity data found.</td>
                                </tr>
                            </tbody>
                        </table>
                    </adaptive-table>
                </div>
            </div>
        </div>

        <div class="crm-toolbar">
            <h4 class="crm-section-title">Sales Leads</h4>
            <button @click="openCreateLeadModal" class="btn btn-primary">Add Lead</button>
        </div>
        <div class="crm-search-row">
            <div class="crm-search">
                <i class="bi bi-search crm-search-icon"></i>
                <input type="text" class="form-control crm-search-input" v-model="leadSearch" placeholder="Search leads by client, contact, email, phone, or status">
            </div>
            <span class="crm-search-count-badge">{{ filteredLeads.length }} Records</span>
            <button class="crm-export-btn" :disabled="filteredLeads.length === 0" @click="exportLeads"><i class="bi bi-file-earmark-spreadsheet"></i>Export Excel</button>
        </div>

        <adaptive-table title="Sales Leads" :row-count="filteredLeads.length">
            <table class="table table-hover crm-table">
                <thead>
                    <tr>
                        <th>Client</th>
                        <th v-if="store.hasRole(['Admin'])">Created By</th>
                        <th>Contact</th>
                        <th>Email</th>
                        <th>Phone</th>
                        <th>Status</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    <tr v-for="lead in filteredLeads" :key="lead.id">
                        <td>{{ lead.client_company }}</td>
                        <td v-if="store.hasRole(['Admin'])">{{ lead.owner }}</td>
                        <td>{{ lead.contact_person }}</td>
                        <td>{{ lead.email }}</td>
                        <td>{{ lead.phone }}</td>
                        <td><span :class="getStatusClass(lead.status)">{{ lead.status }}</span></td>
                        <td>
                            <div class="crm-action-stack">
                            <button class="btn btn-sm crm-action-btn crm-action-btn-outline" @click="viewFollowups(lead)">Activity</button>
                            <button class="btn btn-sm crm-action-btn crm-action-btn-outline" @click="openEditLeadModal(lead)">Edit Lead</button>
                            <button v-if="store.hasRole(['Admin'])" class="btn btn-sm crm-action-btn crm-action-btn-danger" @click="deleteLead(lead)">Delete</button>
                            </div>
                        </td>
                    </tr>
                     <tr v-if="filteredLeads.length === 0">
                        <td :colspan="store.hasRole(['Admin']) ? 7 : 6" class="text-center py-4">No leads found.</td>
                     </tr>
                </tbody>
            </table>
        </adaptive-table>

        <!-- Add Lead Modal -->
        <div v-if="showLeadModal" class="modal fade show crm-modal" style="display: block; background: rgba(14,23,38,0.45);">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title">{{ editingLeadId ? 'Edit Sales Lead' : 'New Sales Lead' }}</h5>
                        <button type="button" class="btn-close" @click="showLeadModal = false"></button>
                    </div>
                    <div class="modal-body">
                         <form @submit.prevent="saveLead">
                            <div class="mb-3">
                                <label>Company Name</label>
                                <input type="text" v-model="leadForm.client_company" class="form-control" required>
                            </div>
                            <div class="mb-3">
                                <label>Contact Person</label>
                                <input type="text" v-model="leadForm.contact_person" class="form-control" required>
                            </div>
                             <div class="mb-3">
                                <label>Email</label>
                                <input type="email" v-model="leadForm.email" class="form-control" required>
                            </div>
                            <div class="mb-3">
                                <label>Phone</label>
                                <input type="text" v-model="leadForm.phone" class="form-control" required>
                            </div>
                            <div class="mb-3">
                                <label>Location</label>
                                <input type="text" v-model="leadForm.location" class="form-control">
                            </div>
                            <div class="mb-3">
                                <label>Website</label>
                                <input type="text" v-model="leadForm.website" class="form-control" placeholder="https://example.com">
                            </div>
                            <div class="mb-3">
                                <label>Social Links</label>
                                <textarea v-model="leadForm.social_links" class="form-control" rows="2" placeholder="LinkedIn, Twitter, or other links"></textarea>
                            </div>
                            <div class="mb-3">
                                <label>SPOC Details</label>
                                <textarea v-model="leadForm.spoc_details" class="form-control" rows="2" placeholder="Decision maker, team details, notes"></textarea>
                            </div>
                            <div class="mb-3">
                                <label class="form-label fw-semibold">Status</label>
                                <compact-select
                                    v-model="leadForm.status"
                                    :options="leadStatusOptions"
                                    placeholder="Select Status"
                                    width="100%"
                                ></compact-select>
                            </div>
                            <button type="submit" class="btn btn-primary">{{ editingLeadId ? 'Save Changes' : 'Create Lead' }}</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>

        <!-- Follow-up Modal -->
        <div v-if="showFollowupModal" class="modal fade show crm-modal" style="display: block; background: rgba(14,23,38,0.45);">
            <div class="modal-dialog modal-lg">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title">Activity for {{ selectedLead?.client_company }}</h5>
                        <button type="button" class="btn-close" @click="showFollowupModal = false"></button>
                    </div>
                    <div class="modal-body">
                        <div class="mb-4">
                            <h6>History</h6>
                            <div class="crm-search mb-3">
                                <i class="bi bi-search crm-search-icon"></i>
                                <input type="text" class="form-control crm-search-input" v-model="followupSearch" placeholder="Search follow-up history by date, notes, or status">
                            </div>
                            <ul class="list-group">
                                <li class="list-group-item" v-for="fu in filteredFollowups" :key="fu.id">
                                    <div class="d-flex w-100 justify-content-between">
                                        <small>{{ fu.scheduled_at }}</small>
                                        <span class="badge bg-secondary">{{ fu.status }}</span>
                                    </div>
                                    <p class="mb-1">{{ fu.notes }}</p>
                                </li>
                                <li v-if="filteredFollowups.length === 0" class="list-group-item">No history.</li>
                            </ul>
                        </div>
                        
                        <hr>
                        
                        <h6>Schedule Follow-up</h6>
                        <form @submit.prevent="addFollowup">
                            <div class="row">
                                <div class="col-md-5 mb-3">
                                    <label>Date & Time</label>
                                    <calendar-field v-model="fuForm.scheduled_at" type="datetime-local" required></calendar-field>
                                </div>
                                <div class="col-md-7 mb-3">
                                    <label>Notes</label>
                                    <input type="text" v-model="fuForm.notes" class="form-control" placeholder="Call notes..." required>
                                </div>
                            </div>
                            <button type="submit" class="btn btn-primary btn-sm">Add Note</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        
    </div>
    `,
    data() {
        return {
            leads: [],
            followups: [],
            selectedLead: null,
            showLeadModal: false,
            showFollowupModal: false,
            leadSearch: '',
            followupSearch: '',
            employeeReportSearch: '',
            editingLeadId: null,
            leadStats: {
                total_leads: 0,
                status_breakdown: {},
                employee_performance: []
            },
            leadForm: {
                client_company: '',
                contact_person: '',
                email: '',
                phone: '',
                location: '',
                website: '',
                social_links: '',
                spoc_details: '',
                status: 'New'
            },
            leadStatusOptions: ['New', 'Contacted', 'Interested', 'Converted', 'Lost'],
            fuForm: {},
            store,
            todayDate: new Date().toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })
        }
    },
    mounted() {
        this.fetchLeads();
        if (this.store.hasRole(['Admin', 'Manager'])) {
            this.fetchLeadStats();
        }
    },
    computed: {
        filteredLeads() {
            const q = this.leadSearch.toLowerCase().trim();
            if (!q) return this.leads;
            return this.leads.filter(lead =>
                (lead.client_company || '').toLowerCase().includes(q) ||
                (lead.owner || '').toLowerCase().includes(q) ||
                (lead.contact_person || '').toLowerCase().includes(q) ||
                (lead.email || '').toLowerCase().includes(q) ||
                (lead.phone || '').toLowerCase().includes(q) ||
                (lead.status || '').toLowerCase().includes(q)
            );
        },
        filteredEmployeePerformance() {
            const q = this.employeeReportSearch.toLowerCase().trim();
            if (!q) return this.leadStats.employee_performance;
            return this.leadStats.employee_performance.filter(item =>
                (item.employee_name || '').toLowerCase().includes(q) ||
                String(item.lead_count || '').includes(q)
            );
        },
        filteredFollowups() {
            const q = this.followupSearch.toLowerCase().trim();
            if (!q) return this.followups;
            return this.followups.filter(fu =>
                (fu.scheduled_at || '').toLowerCase().includes(q) ||
                (fu.notes || '').toLowerCase().includes(q) ||
                (fu.status || '').toLowerCase().includes(q)
            );
        }
    },
    methods: {
        getEmptyLeadForm() {
            return {
                client_company: '',
                contact_person: '',
                email: '',
                phone: '',
                location: '',
                website: '',
                social_links: '',
                spoc_details: '',
                status: 'New'
            };
        },
        async fetchLeads() {
            try {
                const res = await axios.get('/api/sales/leads');
                this.leads = res.data;
            } catch (err) { console.error("Error fetching leads", err); }
        },
        async fetchLeadStats() {
            try {
                const res = await axios.get('/api/sales/stats');
                this.leadStats = res.data || {
                    total_leads: 0,
                    status_breakdown: {},
                    employee_performance: []
                };
            } catch (err) {
                console.error("Error fetching sales stats", err);
            }
        },
        openCreateLeadModal() {
            this.editingLeadId = null;
            this.leadForm = this.getEmptyLeadForm();
            this.showLeadModal = true;
        },
        openEditLeadModal(lead) {
            this.editingLeadId = lead.id;
            this.leadForm = {
                client_company: lead.client_company || '',
                contact_person: lead.contact_person || '',
                email: lead.email || '',
                phone: lead.phone || '',
                location: lead.location || '',
                website: lead.website || '',
                social_links: lead.social_links || '',
                spoc_details: lead.spoc_details || '',
                status: lead.status || 'New'
            };
            this.showLeadModal = true;
        },
        async saveLead() {
            try {
                if (this.editingLeadId) {
                    await axios.put(`/api/sales/leads/${this.editingLeadId}`, this.leadForm);
                } else {
                    await axios.post('/api/sales/leads', this.leadForm);
                }
                this.showLeadModal = false;
                this.editingLeadId = null;
                this.leadForm = this.getEmptyLeadForm();
                this.fetchLeads();
                if (this.store.hasRole(['Admin', 'Manager'])) this.fetchLeadStats();
            } catch (err) {
                alert(err.response?.data?.message || 'Failed to save lead');
            }
        },
        async deleteLead(lead) {
            if (!confirm(`Are you sure you want to delete the lead for ${lead.client_company}?`)) return;
            try {
                await axios.delete(`/api/sales/leads/${lead.id}`);
                this.fetchLeads();
                if (this.store.hasRole(['Admin', 'Manager'])) this.fetchLeadStats();
            } catch (err) {
                alert(err.response?.data?.message || 'Failed to delete lead');
            }
        },
        async viewFollowups(lead) {
            this.selectedLead = lead;
            try {
                const res = await axios.get(`/api/sales/leads/${lead.id}/followups`);
                this.followups = res.data;
                this.showFollowupModal = true;
            } catch (err) { alert('Failed to fetch history'); }
        },
        async addFollowup() {
            if (!this.selectedLead) return;
            // Ensure we strictly send YYYY-MM-DD HH:MM, dropping any seconds attached by the browser
            let formattedDate = this.fuForm.scheduled_at.replace('T', ' ');
            if (formattedDate.length > 16) {
                formattedDate = formattedDate.substring(0, 16);
            }
            try {
                await axios.post(`/api/sales/leads/${this.selectedLead.id}/followups`, {
                    scheduled_at: formattedDate,
                    notes: this.fuForm.notes
                });
                this.fuForm = {};
                this.viewFollowups(this.selectedLead); // Refresh list
            } catch (err) { alert('Failed to add follow-up'); }
        },
        getStatusClass(status) {
            return {
                'badge': true,
                'bg-info': status === 'New',
                'bg-warning': status === 'Contacted',
                'bg-primary': status === 'Interested',
                'bg-success': status === 'Converted',
                'bg-danger': status === 'Lost'
            }
        },
        exportEmployeePerformance() {
            exportToExcel({
                data: this.filteredEmployeePerformance,
                columns: [
                    { header: 'Employee', field: 'employee_name' },
                    { header: 'Leads Generated', field: 'lead_count' }
                ],
                fileName: 'leads-by-employee'
            });
        },
        exportLeads() {
            const columns = [
                { header: 'Client', field: 'client_company' }
            ];
            if (this.store.hasRole(['Admin'])) {
                columns.push({ header: 'Created By', field: 'owner' });
            }
            columns.push(
                { header: 'Contact', field: 'contact_person' },
                { header: 'Email', field: 'email' },
                { header: 'Phone', field: 'phone' },
                { header: 'Location', field: 'location' },
                { header: 'Website', field: 'website' },
                { header: 'Status', field: 'status' }
            );
            exportToExcel({
                data: this.filteredLeads,
                columns,
                fileName: 'sales-leads'
            });
        }
    }
};
// import { store } from '../store.js';

// export default {
//     template: `
//     <div>
//         <div class="row mb-4 animate__animated animate__fadeIn">
//             <div class="col-12 d-flex justify-content-between align-items-center">
//                 <div>
//                     <h2 class="mb-1 text-primary">Sales & Business Dashboard</h2>
//                     <p class="text-muted mb-0">Welcome back, <strong>{{ store.user?.full_name || store.user?.username }}</strong></p>
//                 </div>
//                 <div class="text-end d-none d-md-block">
//                     <span class="badge bg-white text-dark border p-2 shadow-sm">
//                         <i class="bi bi-calendar3 me-2 text-primary"></i>{{ todayDate }}
//                     </span>
//                 </div>
//             </div>
//         </div>

//         <div class="d-flex justify-content-between mb-3">
//             <h4>Sales Leads</h4>
//             <button @click="showLeadModal = true" class="btn btn-primary">Add Lead</button>
//         </div>

//         <div class="table-responsive bg-white shadow-sm rounded">
//             <table class="table table-hover mb-0">
//                 <thead>
//                     <tr>
//                         <th>Client</th>
//                         <th>Contact</th>
//                         <th>Email</th>
//                         <th>Phone</th>
//                         <th>Status</th>
//                         <th>Actions</th>
//                     </tr>
//                 </thead>
//                 <tbody>
//                     <tr v-for="lead in leads" :key="lead.id">
//                         <td>{{ lead.client_company }}</td>
//                         <td>{{ lead.contact_person }}</td>
//                         <td>{{ lead.email }}</td>
//                         <td>{{ lead.phone }}</td>
//                         <td><span :class="getStatusClass(lead.status)">{{ lead.status }}</span></td>
//                         <td>
//                             <button class="btn btn-sm btn-outline-info me-1" @click="viewFollowups(lead)">Activity</button>
//                             <button class="btn btn-sm btn-outline-secondary" @click="editLead(lead)">Edit</button>
//                         </td>
//                     </tr>
//                     <tr v-if="leads.length === 0">
//                         <td colspan="6" class="text-center py-4">No leads found.</td>
//                     </tr>
//                 </tbody>
//             </table>
//         </div>

//         <!-- Add Lead Modal -->
//         <div v-if="showLeadModal" class="modal fade show" style="display: block; background: rgba(0,0,0,0.5);">
//             <div class="modal-dialog">
//                 <div class="modal-content">
//                     <div class="modal-header">
//                         <h5 class="modal-title">New Sales Lead</h5>
//                         <button type="button" class="btn-close" @click="showLeadModal = false"></button>
//                     </div>
//                     <div class="modal-body">
//                         <form @submit.prevent="createLead">
//                             <div class="mb-3">
//                                 <label>Company Name</label>
//                                 <input type="text" v-model="leadForm.client_company" class="form-control" required>
//                             </div>

//                             <div class="mb-3">
//                                 <label>Contact Person</label>
//                                 <input type="text" v-model="leadForm.contact_person" class="form-control" required>
//                             </div>

//                             <div class="mb-3">
//                                 <label>Email</label>
//                                 <input type="email" v-model="leadForm.email" class="form-control" required>
//                             </div>

//                             <div class="mb-3">
//                                 <label>Phone</label>
//                                 <input 
//                                     type="tel"
//                                     v-model="leadForm.phone"
//                                     class="form-control"
//                                     maxlength="10"
//                                     pattern="[0-9]{10}"
//                                     inputmode="numeric"
//                                     @input="leadForm.phone = leadForm.phone.replace(/[^0-9]/g, '')"
//                                     placeholder="Enter 10 digit phone number"
//                                     required
//                                 >
//                             </div>

//                             <button type="submit" class="btn btn-primary">Create</button>
//                         </form>
//                     </div>
//                 </div>
//             </div>
//         </div>

//         <!-- Follow-up Modal -->
//         <div v-if="showFollowupModal" class="modal fade show" style="display: block; background: rgba(0,0,0,0.5);">
//             <div class="modal-dialog modal-lg">
//                 <div class="modal-content">
//                     <div class="modal-header">
//                         <h5 class="modal-title">Activity for {{ selectedLead?.client_company }}</h5>
//                         <button type="button" class="btn-close" @click="showFollowupModal = false"></button>
//                     </div>
//                     <div class="modal-body">

//                         <div class="mb-4">
//                             <h6>History</h6>
//                             <ul class="list-group">
//                                 <li class="list-group-item" v-for="fu in followups" :key="fu.id">
//                                     <div class="d-flex w-100 justify-content-between">
//                                         <small>{{ fu.scheduled_at }}</small>
//                                         <span class="badge bg-secondary">{{ fu.status }}</span>
//                                     </div>
//                                     <p class="mb-1">{{ fu.notes }}</p>
//                                 </li>
//                                 <li v-if="followups.length === 0" class="list-group-item">No history.</li>
//                             </ul>
//                         </div>

//                         <hr>

//                         <h6>Schedule Follow-up</h6>
//                         <form @submit.prevent="addFollowup">
//                             <div class="row">
//                                 <div class="col-md-5 mb-3">
//                                     <label>Date & Time</label>
//                                     <input type="datetime-local" v-model="fuForm.scheduled_at" class="form-control" required>
//                                 </div>

//                                 <div class="col-md-7 mb-3">
//                                     <label>Notes</label>
//                                     <input type="text" v-model="fuForm.notes" class="form-control" placeholder="Call notes..." required>
//                                 </div>
//                             </div>

//                             <button type="submit" class="btn btn-primary btn-sm">Add Note</button>
//                         </form>

//                     </div>
//                 </div>
//             </div>
//         </div>

//     </div>
//     `,
//     data() {
//         return {
//             leads: [],
//             followups: [],
//             selectedLead: null,
//             showLeadModal: false,
//             showFollowupModal: false,
//             leadForm: {},
//             fuForm: {},
//             store,
//             todayDate: new Date().toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })
//         }
//     },
//     mounted() {
//         this.fetchLeads();
//     },
//     methods: {
//         async fetchLeads() {
//             try {
//                 const res = await axios.get('/api/sales/leads');
//                 this.leads = res.data;
//             } catch (err) { console.error("Error fetching leads", err); }
//         },
//         async createLead() {
//             try {
//                 await axios.post('/api/sales/leads', this.leadForm);
//                 this.showLeadModal = false;
//                 this.leadForm = {};
//                 this.fetchLeads();
//             } catch (err) { alert('Failed to create lead'); }
//         },
//         async viewFollowups(lead) {
//             this.selectedLead = lead;
//             try {
//                 const res = await axios.get(`/api/sales/leads/${lead.id}/followups`);
//                 this.followups = res.data;
//                 this.showFollowupModal = true;
//             } catch (err) { alert('Failed to fetch history'); }
//         },
//         async addFollowup() {
//             if (!this.selectedLead) return;

//             let formattedDate = this.fuForm.scheduled_at.replace('T', ' ');
//             if (formattedDate.length > 16) {
//                 formattedDate = formattedDate.substring(0, 16);
//             }

//             try {
//                 await axios.post(`/api/sales/leads/${this.selectedLead.id}/followups`, {
//                     scheduled_at: formattedDate,
//                     notes: this.fuForm.notes
//                 });

//                 this.fuForm = {};
//                 this.viewFollowups(this.selectedLead);
//             } catch (err) { alert('Failed to add follow-up'); }
//         },
//         editLead(lead) {
//             const newStatus = lead.status === 'New' ? 'Contacted' : 'Converted';
//             axios.put(`/api/sales/leads/${lead.id}`, { status: newStatus })
//                 .then(() => this.fetchLeads());
//         },
//         getStatusClass(status) {
//             return {
//                 'badge': true,
//                 'bg-info': status === 'New',
//                 'bg-warning': status === 'Contacted',
//                 'bg-success': status === 'Converted',
//                 'bg-danger': status === 'Lost'
//             }
//         }
//     }
// };
